/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package profpac;

import connexion.Connexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MBS
 */
public class Accprof extends javax.swing.JFrame {
public String  mat ,clas;
   public int idcl,idmat,profi;




    public Accprof() {
        initComponents();
       // Remcre();
    }
public void Remcre(){
     try{
        Connexion co =new Connexion();
        Statement stmt=co.con.createStatement();
      
        String chsql="SELECT * FROM prof_clas_mat join professeur on (professeur.prof_id=prof_clas_mat.prof_id)" +
" join matiere on (matiere.mat_id=prof_clas_mat.mat_id)" +
" join classroom on (classroom.clas_id=prof_clas_mat.clas_id)" +
" WHERE professeur.prof_email like '"+lblemail.getText()+"'";
        ResultSet res= stmt.executeQuery(chsql);
        DefaultTableModel d=(DefaultTableModel) tbcl_mat.getModel();
        while(d.getRowCount()>0){
                 d.removeRow(0);
            
        }

         while(res.next()){
             try{
        Connexion cod =new Connexion();
        Statement stmtd=cod.con.createStatement();

        String chsqld=" SELECT * FROM classroom where clas_id="+res.getString("clas_id");
        ResultSet resd= stmtd.executeQuery(chsqld);

         if(resd.next()){
            clas =resd.getString("clas_nom");
           
           
         }
            

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this,"error "+e.getMessage());
    }   try{
        Connexion cod =new Connexion();
        Statement stmtd=cod.con.createStatement();

        String chsqlm=" SELECT * FROM matiere where mat_id="+res.getString("mat_id");
        ResultSet resdm= stmtd.executeQuery(chsqlm);

         if(resdm.next()){
            mat =resdm.getString("mat_nom");
           
           
         }
            

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this,"error "+e.getMessage());
    }
            String tbData[]={clas,mat};
            DefaultTableModel tbmodel=(DefaultTableModel) tbcl_mat.getModel();
            tbmodel.addRow(tbData);
            }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this,"error "+e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblprof = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcl_mat = new javax.swing.JTable();
        btnexamnew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblprof.setText("jLabel1");

        lblemail.setText("jLabel1");

        tbcl_mat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Classe", "Matiere"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbcl_mat);
        if (tbcl_mat.getColumnModel().getColumnCount() > 0) {
            tbcl_mat.getColumnModel().getColumn(0).setResizable(false);
            tbcl_mat.getColumnModel().getColumn(1).setResizable(false);
        }

        btnexamnew.setText("Creer un exam");
        btnexamnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexamnewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblprof)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblemail)
                        .addGap(171, 171, 171))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnexamnew)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprof)
                    .addComponent(lblemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnexamnew)
                .addGap(236, 236, 236))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexamnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexamnewActionPerformed
          int row =tbcl_mat.getSelectedRow();
         if(row>=0){
                     String cellcl= tbcl_mat.getModel().getValueAt(row, 0).toString();
                   String cellmat= tbcl_mat.getModel().getValueAt(row, 1).toString();
            InfoExam ne=new InfoExam();
            ne.setVisible(true);
         try{
        Connexion co =new Connexion();
        Statement stmt=co.con.createStatement();

        String chsql=" select *  from classroom "
                + " where clas_nom like '"+cellcl+"'";
        ResultSet res= stmt.executeQuery(chsql);

         if(res.next()){
            ne.idcl=res.getInt("clas_id");
          try{
        Connexion cod =new Connexion();
        Statement stmtd=cod.con.createStatement();

        String chsqld=" select *  from matiere "
                + " where mat_nom like '"+cellmat+"'";
        ResultSet resd= stmtd.executeQuery(chsqld);

         if(resd.next()){
            ne.idmat=resd.getInt("mat_id");
           
         }
            

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this,"error "+e.getMessage());
    }
            try{
        Connexion cod =new Connexion();
        Statement stmtd=cod.con.createStatement();

        String chsqld=" select *  from professeur "
                + " where prof_email like '"+lblemail.getText()+"'";
        ResultSet resd= stmtd.executeQuery(chsqld);

         if(resd.next()){
            ne.profi=resd.getInt("prof_id");
           
         }
            

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this,"error "+e.getMessage());
    }
         }
            

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this,"error "+e.getMessage());
    }
        }else{
         JOptionPane.showMessageDialog(this,"veillez selectionner une ligne");}
         
         
         
         
         
    }//GEN-LAST:event_btnexamnewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accprof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accprof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accprof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accprof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accprof().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexamnew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblemail;
    public javax.swing.JLabel lblprof;
    private javax.swing.JTable tbcl_mat;
    // End of variables declaration//GEN-END:variables
}
